---

- import_playbook: boilerplate.yml

- hosts: tempest-runner
  vars:
    openrc_location: "{{ ansible_env.HOME }}/openrc"
    results_location: "{{ ansible_env.HOME }}/rally-results"
  tasks:
    - block:
      - name: create a directory to house the results on the remote
        file:
          path: "{{ results_location }}"
          state: directory
          mode: 0777
      
      - name: create an openrc file
        copy:
          content: "{{ openrc_file_contents }}"
          dest: "{{ openrc_location }}"

      - name: run tempest
        command: |-
           docker run -it --rm --entrypoint=/usr/bin/rally-verify-wrapper.sh
           -v "{{ results_location }}:/home/rally/artefacts"
           -v "{{ openrc_location }}:/home/rally/openrc:ro"
           -e "TEMPEST_PATTERN={{ pattern | default('') }}"
           gwee/rally
        become: true

      - name: fixup permissions
        file:
          path: "{{ results_location }}"
          owner: "{{ ansible_user }}"
          recurse: true
        become: true
        
      - name: synchronize files
        synchronize:
          src: "{{ results_location }}"
          dest: ./
          mode: pull
          archive: no
          recursive: true
          # For jump host
          use_ssh_args: true
            
      always:
        - name: cleanup results
          file:
            path: "{{ results_location }}"
            state: absent

        - name: remove openrc file
          file:
            path: "{{ openrc_location }}"
            state: absent


