---

- import_playbook: boilerplate.yml

- hosts: tempest-runner
  vars:
    openrc_location: "{{ ansible_env.HOME }}/openrc"
    results_location: "{{ ansible_env.HOME }}/rally-results"
    tempest_config_location: "{{ ansible_env.HOME }}/tempest.conf"
    load_list_location: "{{ ansible_env.HOME }}/tempest-load-list"
    skip_list_location: "{{ ansible_env.HOME }}/tempest-skip-list"
    work_location_defaulted: "{{ work_location | default(lookup('env', 'PWD')) }}"
  tasks:
    - block:
      - name: create a directory to house the results on the remote
        file:
          path: "{{ results_location }}"
          state: directory
          mode: 0777

      - name: create an openrc file
        copy:
          content: "{{ openrc_file_contents }}"
          dest: "{{ openrc_location }}"

      - name: Copy load list to remote host
        copy:
          src: "{{ tempest_load_list_file }}"
          dest: "{{ load_list_location }}"
        when: tempest_load_list_file is defined

      - name: (optional) create tempest overrides
        copy:
          content: "{{ tempest_config_contents }}"
          dest: "{{ tempest_config_location }}"
        when: tempest_config_contents is defined

      - name: (optional) create tempest skip list
        copy:
          content: "{{ tempest_skip_list_contents }}"
          dest: "{{ skip_list_location }}"
        when: tempest_skip_list_contents is defined

      - name: run tempest
        command: |-
           docker run -it --rm --entrypoint=/usr/bin/rally-verify-wrapper.sh
           -v "{{ results_location }}:/home/rally/artifacts"
           -v "{{ openrc_location }}:/home/rally/openrc:ro"
           {% if tempest_config_contents is defined -%}
           -v {{ tempest_config_location }}:/home/rally/tempest-overrides.conf:ro
           {% endif -%}
           {% if tempest_skip_list_contents is defined -%}
           -v {{ skip_list_location }}:/home/rally/tempest-skip-list:ro
           {% endif -%}
           {% if tempest_load_list_file is defined -%}
           -v {{ load_list_location }}:/home/rally/tempest-load-list:ro
           {% endif -%}
           -e "TEMPEST_PATTERN={{ tempest_pattern | default('') }}"
           -e "TEMPEST_CONCURRENCY={{ tempest_concurrency | default('') }}"
           gwee/rally
        become: true

      - name: fixup permissions
        file:
          path: "{{ results_location }}"
          owner: "{{ ansible_user }}"
          recurse: true
        become: true

      - name: synchronize files
        synchronize:
          src: "{{ results_location }}"
          dest: "{{ work_location_defaulted }}"
          mode: pull
          archive: no
          recursive: true
          # For jump host
          use_ssh_args: true

      always:
        - name: cleanup results
          file:
            path: "{{ results_location }}"
            state: absent

        - name: cleanup load list
          file:
            path: "{{ load_list_location }}"
            state: absent

        - name: cleanup skip list
          file:
            path: "{{ skip_list_location }}"
            state: absent

        - name: clean up tempest overrides
          file:
            path: "{{ tempest_config_location }}"
            state: absent

        - name: remove openrc file
          file:
            path: "{{ openrc_location }}"
            state: absent


