---
- hosts: cumulus-seed
  gather_facts: false
  tasks:
    - name: Ensure ssh host key known
      delegate_to: localhost
      lineinfile:
        dest: ~/.ssh/known_hosts
        create: yes
        state: present
        line: "{{ item }}"
      no_log: true
      with_items: "{{ host_keys }}"
    - pause:
        minutes: 5

- hosts: cumulus-seed
  tasks:
    - file:
        path: /tmp/hello-from-jenkins
        state: touch
