---
- hosts: cumulus-seed
  gather_facts: false
  tasks:
    - name: Ensure ssh host key known
      delegate_to: localhost
      lineinfile:
        dest: ~/.ssh/known_hosts
        create: yes
        state: present
        line: "{{ item }}"
      no_log: true
      with_items: "{{ host_keys }}"
    - set_fact:
        ansible_ssh_extra_args: "{{ secrets_ssh_args % ansible_ssh_private_key_file }}"

- hosts: cumulus-seed
  tasks:
    - file:
        path: /tmp/hello-from-jenkins
        state: touch
